### ISSUE TITLE
JPEG with invalid SOS parameters triggers double-free flaw

### ISSUE THREAD

**Issue by geeknik** [dlbeer/quirc#35]
Compiled with afl-clang-fast on Debian 8 x64. Triggered with `5174ba7`.

./inspect ![test000.jpeg](https://cloud.githubusercontent.com/assets/466878/26616504/ab0d5804-4594-11e7-8320-0f24cf3e6def.jpeg)

```
quirc inspection program
Copyright (C) 2010-2012 Daniel Beer <dlbeer@gmail.com>
Library version: 1.0

JPEG error: Invalid SOS parameters for sequential JPEGJPEG error: Unsupported marker type 0x30=================================================================
==32096==ERROR: AddressSanitizer: attempting double-free on 0x61600000f980 in thread T0:
    #0 0x4a0d9b in free (/root/quirc/inspect+0x4a0d9b)
    #1 0x7f0e97f65734 in fclose /build/glibc-KShDyh/glibc-2.19/libio/iofclose.c:85
    #2 0x4bf587 in load_jpeg /root/quirc/tests/dbgutil.c:160:2
    #3 0x4c1487 in main /root/quirc/tests/inspect.c:243:12
    #4 0x7f0e97f1db44 in __libc_start_main /build/glibc-KShDyh/glibc-2.19/csu/libc-start.c:287
    #5 0x4be69c in _start (/root/quirc/inspect+0x4be69c)

0x61600000f980 is located 0 bytes inside of 568-byte region [0x61600000f980,0x61600000fbb8)
freed by thread T0 here:
==32096==AddressSanitizer CHECK failed: /tmp/buildd/llvm-toolchain-3.5-3.5/projects/compiler-rt/lib/asan/asan_allocator2.cc:203 "((id)) != (0)" (0x0, 0x0)
    #0 0x4a8473 in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/root/quirc/inspect+0x4a8473)
    #1 0x4aeec1 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/root/quirc/inspect+0x4aeec1)
    #2 0x43a519 in __asan::AsanChunkView::GetFreeStack(__sanitizer::StackTrace*) (/root/quirc/inspect+0x43a519)
    #3 0x4a44dd in __asan::DescribeHeapAddress(unsigned long, unsigned long) (/root/quirc/inspect+0x4a44dd)
    #4 0x4a4d9a in __asan::ReportDoubleFree(unsigned long, __sanitizer::StackTrace*) (/root/quirc/inspect+0x4a4d9a)
    #5 0x43ce8d in __asan::ReportInvalidFree(void*, unsigned char, __sanitizer::StackTrace*) (/root/quirc/inspect+0x43ce8d)
    #6 0x43b845 in __asan::Deallocate(void*, __sanitizer::StackTrace*, __asan::AllocType) (/root/quirc/inspect+0x43b845)
    #7 0x4a0e5c in free (/root/quirc/inspect+0x4a0e5c)
    #8 0x7f0e97f65734 in fclose /build/glibc-KShDyh/glibc-2.19/libio/iofclose.c:85
    #9 0x4bf587 in load_jpeg /root/quirc/tests/dbgutil.c:160:2
    #10 0x4c1487 in main /root/quirc/tests/inspect.c:243:12
    #11 0x7f0e97f1db44 in __libc_start_main /build/glibc-KShDyh/glibc-2.19/csu/libc-start.c:287
    #12 0x4be69c in _start (/root/quirc/inspect+0x4be69c)
```

**Comment by dlbeer** [comment]
Thanks for finding this -- just fixed in commit ffc2f9b68a4eabd7b31f3390ca9ca2738ed2a79e.
